level = [
   "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",   
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g", 
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g", 
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g     gg                                                                                                                                          g",
   "g     gg                                                  ss                                                                                      g",
   "g     ss          ss                    ss                                                                                                        g",
   "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"]
