level = [
   "ggggggggggggggggggggggggg",   
   "g            -----------g", 
   "g                       g",
   "g            ----    ---g",
   "g                       g",
   "g     *                 g",
   "g                       g",
   "g            --         g",
   "g                       g",
   "gg              *       g",
   "g                       g",
   "g                   --- g",
   "g                       g",
   "g                       g",
   "g      ---              g",
   "g       *               g",
   "g   -----------         g",
   "g                       g",
   "g                -      g",
   "g                   --  g",
   "g                       g",
   "g                       g",
   "-------------------------"]
