level = [
   "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",   
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g", 
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g", 
   "g                                                                                                                                                 g",
   "g                                                                                                                                                 g",
   "g       ss    ss                                                                                                                                      g",
   "g                                                         ss                                                                                      g",
   "g                 ss                    ss                                                                                                        g",
   "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"]
